FROM golang:latest

RUN mkdir / app
WORKDIR /app

RUN go get github.com/gin-gonic/gin
RUN go get github.com/jinzhu/gorm/dialects/mysql
RUN go get github.com/jinzhu/gorm
RUN go get github.com/gin-contrib/cors