version: '3'

services: 
  go:
      build: 
          context: .
          dockerfile: DockerFile
      container_name: svelte_go_api
      command: /bin/sh -c "go run main.go"
      stdin_open: true
      tty: true
      volumes: 
        - .:/app
      networks: 
        - svelte_go_network
      ports:
        - 8080:8080
      depends_on: 
        - "mysql"

  mysql:
      image: mysql:8
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: TaskList
        MYSQL_USER: root
        TZ: 'Asia/Tokyo' 
      command: mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:  
        - db-data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306

volumes:
  db-data:
    driver: local

networks: 
  svelte-go-network:
    name: svelte_go_network